public class ConstantClass {
    public ConstantClass() {}

    public static String customerRecType     = 'Customer';

    public static String activeStatus        = 'Active';
    public static String tutionFeeType       = 'Tuition Fee';
    public static String depositFeeType      = 'Deposit';
    public static String ScheduledStatus     = 'Scheduled';
    public static String termFrequency       = 'Term';

    public static String earlyBirdDiscount   = 'Early Bird';
    public static String amountFormat        = 'Amount';
    public static String percentFormat       = 'Percent';

    public static String referralType        = 'Referral';
    public static String promoType           = 'Promo';
    public static String discountType        = 'Discount';

    public static String monthlyFrequency    = 'Monthly';

    public static String newEnrollmentInvType= 'New Enrollment';
    public static String dueStatus           = 'Due';
    public static String paidStatus          = 'Paid';

    public static String enrolledStatus     = 'Enrolled';
    public static String ongoingClsType     = 'Ongoing';
    public static String monthClsType       = 'Month';

    public static String notAttendedStatus  = 'Not Attended';
    public static String feeType            = 'Fee';
}